spring.application.name=STUDENT-SERVICE

server.port=8081

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Optional but recommended
eureka.instance.prefer-ip-address=true

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.com.practice.studentservice=DEBUG
